apiVersion: v1
kind: Pod
metadata:
  name: admision-violate
spec:
  containers:
    - name: malicious
      image: golang:1.23.1-bullseye
      command:
        - sleep
        - infinity
      securityContext:
        privileged: true