apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - namespace.yml
  - destination.yml


helmCharts:
- name: odigos
  repo: https://odigos-io.github.io/odigos/
  releaseName: odigos
  namespace: observability
  version: v1.0.102
  includeCRDs: true
  valuesFile: values.yml