apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orchestration

resources:
  - namespace.yml
  - provider.yml
  - credentials.yml


helmCharts:
- name: crossplane
  repo: https://charts.crossplane.io/stable
  releaseName: crossplane
  namespace: orchestration
  includeCRDs: true
  # valuesFile: values.yml