apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cman
    namespace: kube-system
    includeCRDs: true
    valuesFile: certValues.yml
  # - name: trust-manager
  #   repo: https://charts.jetstack.io
  #   releaseName: tman
  #   namespace: kube-system
  #   includeCRDs: true
  #   valuesFile: trustValues.yml

resources:
  - issuer.yml
  # - bundle.yml