apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: certmanager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: ca
    namespace: certmanager
    includeCRDs: true
    version: v1.15.3

resources:
  - namespace.yml