apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
 - namespace.yml

helmCharts:
- name: signoz
  repo: https://charts.signoz.io
  releaseName: signoz-obs
  namespace: observability
  valuesFile: values-signoz.yml
- name: k8s-infra
  repo: https://charts.signoz.io
  releaseName: k8s-infra
  namespace: observability
  valuesFile: values-infra.yml