apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - namespace.yml
  # Install clickhouse CRDs
  - charts/signoz/charts/clickhouse/crds/clickhouseinstallations.clickhouse.altinity.com.yaml
  - charts/signoz/charts/clickhouse/crds/clickhouseoperatorconfigurations.clickhouse.altinity.com.yaml
  - charts/signoz/charts/clickhouse/crds/clickhouseinstallationtemplates.clickhouse.altinity.com.yaml


helmCharts:
- name: signoz
  repo: https://charts.signoz.io
  releaseName: signoz-obs
  namespace: observability
  valuesFile: values.yml