openapi: 3.0.3
info:
  title: Library API
  description: API for managing books in a library
  version: 1.0.0
servers:
  - url: http://0.0.0.0:8080/api/v1
    description: Local server

paths:
  /health:
    get:
      summary: healthcheck endpoint
      responses:
        '204':
          description: success
  /books:
    get:
      summary: Get list of all books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Add a new book
      requestBody:
        description: Book to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created successfully
        '400':
          description: Invalid input

  /books/{bookId}:
    get:
      summary: Get details of a specific book
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID of the book to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Details of the book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
    put:
      summary: Update an existing book
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID of the book to update
          schema:
            type: integer
      requestBody:
        description: Updated book details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated successfully
        '400':
          description: Invalid input
        '404':
          description: Book not found
    delete:
      summary: Delete a book
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID of the book to delete
          schema:
            type: integer
      responses:
        '204':
          description: Book deleted successfully
        '404':
          description: Book not found

components:
  schemas:
    Book:
      type: object
      required:
        - id
        - title
        - author
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "The Great Gatsby"
        author:
          type: string
          example: "F. Scott Fitzgerald"
        publishedDate:
          type: string
          format: date
          example: "1925-04-10"
        isbn:
          type: string
          example: "978-0743273565"
        pages:
          type: integer
          example: 180
        language:
          type: string
          example: "English"
