apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cncflab-default

nodes:
- role: control-plane
- role: worker
  image: kindest/node:v1.29.8
  extraPortMappings:
  - containerPort: 80
    hostPort: 3280
  - containerPort: 443
    hostPort: 3443
- role: worker
  image: kindest/node:v1.29.8
  # extraPortMappings:
  # - containerPort: 80
  #   hostPort: 3280
  # - containerPort: 443
  #   hostPort: 3443
- role: worker
  image: kindest/node:v1.29.8
  # extraPortMappings:
  # - containerPort: 80
  #   hostPort: 3280
  # - containerPort: 443
  #   hostPort: 3443