apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-signoz-instrumentation
spec:
  exporter:
    endpoint: signoz-obs-otel-collector.observability:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"