apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    releaseName: kyverno
    namespace: kyverno
    includeCRDs: true
    version: 3.2.5
    valuesFile: value.yml
  - name: kyverno-policies
    repo: https://kyverno.github.io/kyverno/
    releaseName: kyverno-policies
    namespace: kyverno
    includeCRDs: true
    valuesFile: policies.yml

resources:
  - namespace.yml
