apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: tetragon
    repo: https://helm.cilium.io/
    releaseName: tetragon
    namespace: kube-system
    valuesFile: values.yml