apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubearmor

helmCharts:
  - name: kubearmor-operator
    repo: https://kubearmor.github.io/charts
    releaseName: kubearmor-operator
    namespace: kubearmor
    includeCRDs: true
    version: v1.4.1
    valuesFile: value.yml

resources:
  - namespace.yml
  - policy.yml
