apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: deathstar
spec:
  parentRefs:
  - name: cilium-lb
    namespace: kube-system
  - name: traefik-lb
    namespace: traefik
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /v1
    backendRefs:
    - name: deathstar
      port: 80
