apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

# resources:

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    releaseName: cilium
    namespace: kube-system
    valuesFile: values.yml