kubeProxyReplacement: true
operator:
  replicas: 1
  podAnnotations:
    signoz.io/scrape: 'true'
    signoz.io/port: '9963'
    signoz.io/path: /metrics


hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true


ipam:
  mode: kubernetes

ingressController:
  enabled: true
  loadbalancerMode: shared

nodePort:
  enabled: true

l7Proxy: true

prometheus:
  enabled: true

podAnnotations:
  signoz.io/scrape: 'true'
  signoz.io/port: '9962'
  signoz.io/path: /metrics

envoy:
  podAnnotations:
    signoz.io/scrape: 'true'
    signoz.io/port: '9964'
    signoz.io/path: /metrics
